name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run format-check
    - run: npm test
  integration-test:
    name: Integrate Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.8"]
        include:
        - os: macos-12
          swift: "5.8"
        - os: ubuntu-22.04
          swift: "5.8"
        - os: windows-latest
          swift: "5.6.3"
    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm run build && npm run pack-source-map
    - uses: ./
      with:
        swift-version: ${{ matrix.swift }}
    - name: Swift version
      run: swift --version | grep ${{ matrix.swift }} || exit 1
